import { ProductCondition, type Product } from '@/types';

export const sampleProducts: Product[] = [
  {
    id: 'prod-1',
    sellerId: 'seller-1',
    name: 'Ankara Wrap Maxi Skirt',
    description: 'Handcrafted authentic African Ankara wax print wrap skirt. Rich vibrant patterns, adjustable waist ties, and flattering silhouette for casual and festive occasions.',
    category: 'Clothing',
    price: 8500,
    originalPrice: 15000,
    images: [
      'https://images.unsplash.com/photo-1614081781451-29c084a7de30?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=900&q=80',
    ],
    size: 'M',
    condition: ProductCondition.NEW,
    material: '100% Cotton Wax Print',
    color: 'Multi / Gold',
    brand: 'Lagos Heritage',
    quantity: 12,
    sold: 45,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-01'),
    updatedAt: new Date('2026-08-15'),
  },
  {
    id: 'prod-2',
    sellerId: 'seller-2',
    name: 'Genuine Leather Tote Handbag',
    description: 'Structured premium leather shoulder handbag with reinforced handles. Spacious interior with multiple zip pockets, perfect for work, meetings, or shopping.',
    category: 'Bags',
    price: 18000,
    originalPrice: 32000,
    images: [
      '/bag-handbag.jpg',
    ],
    size: 'Medium',
    condition: ProductCondition.LIKE_NEW,
    material: 'Genuine Leather',
    color: 'Rich Brown',
    brand: 'Yaba Classics',
    quantity: 5,
    sold: 28,
    rating: 4.8,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-10'),
    updatedAt: new Date('2026-08-16'),
  },
  {
    id: 'prod-3',
    sellerId: 'seller-3',
    name: 'Chop Corporate Shoes',
    description: 'Comfort meets class. Handcrafted corporate leather lace-up shoes. Flexible anti-slip rubber sole, all-day cushioned insole, and timeless sleek finish for professionals.',
    category: 'Shoes',
    price: 22999,
    originalPrice: 38000,
    images: [
      '/male-shoes-collection.jpg',
    ],
    size: '42',
    condition: ProductCondition.NEW,
    material: 'Full-Grain Leather',
    color: 'Black / Brown / Grey',
    brand: 'Executive Walk',
    quantity: 14,
    sold: 62,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-12'),
    updatedAt: new Date('2026-08-18'),
  },
  {
    id: 'prod-4',
    sellerId: 'seller-4',
    name: 'Folded Office Shirts Pack',
    description: 'Clean, classy, and comfortable. Pack of crisp office shirts in classic stripes and solid blues. Neatly folded, premium breathable cotton with stiff collar.',
    category: 'Shirts',
    price: 9999,
    originalPrice: 20000,
    images: [
      '/folded-shirts-blue.jpg',
      '/casual-shirts-stack.jpg',
    ],
    size: 'L',
    condition: ProductCondition.LIKE_NEW,
    material: 'Crisp Cotton',
    color: 'Sky Blue / Striped',
    brand: 'Savile Row Thrift',
    quantity: 15,
    sold: 89,
    rating: 4.8,
    trending: true,
    published: true,
    createdAt: new Date('2026-07-29'),
    updatedAt: new Date('2026-08-10'),
  },
  {
    id: 'prod-5',
    sellerId: 'seller-5',
    name: 'Executive Two-Piece Suit & Tie',
    description: 'Look rich, spend smart. Tailored two-piece slim fit business suit complete with matching blue necktie and pocket square. Premium wool-blend with immaculate cut.',
    category: 'Suits',
    price: 28500,
    originalPrice: 55000,
    images: [
      '/suit-blue-1.jpg',
      '/suit-grey-1.jpg',
    ],
    size: '42R / L',
    condition: ProductCondition.LIKE_NEW,
    material: 'Wool Blend',
    color: 'Midnight Navy',
    brand: 'Executive Suitmakers',
    quantity: 6,
    sold: 34,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-11'),
    updatedAt: new Date('2026-08-17'),
  },
  {
    id: 'prod-6',
    sellerId: 'seller-6',
    name: 'Chop Casuals Shirt Stack',
    description: 'Look sharp, chop casuals! Premium quality folded casual shirts in versatile colors. Soft on the skin, breathable fabric, durable double stitching, and built for everyday style.',
    category: 'Shirts',
    price: 9999,
    originalPrice: 18000,
    images: [
      '/casual-shirts-colorful.jpg',
      '/casual-shirts-stack.jpg',
    ],
    size: 'Mixed (M & L)',
    condition: ProductCondition.GOOD,
    material: '100% Breathable Cotton',
    color: 'Multi Assorted',
    brand: 'Street Edit',
    quantity: 20,
    sold: 72,
    rating: 4.7,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-07'),
    updatedAt: new Date('2026-08-14'),
  },
  {
    id: 'prod-7',
    sellerId: 'seller-7',
    name: 'Vintage Washed Denim Jeans',
    description: 'Straight-leg vintage wash denim jeans with sturdy brass rivets. Classic five-pocket styling, heavy-duty denim weave, and timeless streetwear look.',
    category: 'Clothing',
    price: 12500,
    originalPrice: 24000,
    images: [
      '/jeans-folded.jpg',
      '/jeans-stack.jpg',
    ],
    size: '32 / 34',
    condition: ProductCondition.GOOD,
    material: 'Heavyweight Denim',
    color: 'Classic Indigo Blue',
    brand: "Levi's Thrift Pick",
    quantity: 16,
    sold: 58,
    rating: 4.6,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-05'),
    updatedAt: new Date('2026-08-12'),
  },
  {
    id: 'prod-8',
    sellerId: 'seller-8',
    name: 'Classic Black Stiletto Heels',
    description: 'Sleek pointed-toe black high heels with padded insole and slender heel. Premium patent finish suited for corporate wear, dinners, and events.',
    category: 'Shoes',
    price: 16000,
    originalPrice: 28000,
    images: [
      '/heels-black-pair.jpg',
      '/heels-black-single.jpg',
    ],
    size: '39',
    condition: ProductCondition.LIKE_NEW,
    material: 'Patent Faux Leather',
    color: 'Glossy Black',
    brand: 'Zara Thrift',
    quantity: 8,
    sold: 41,
    rating: 4.8,
    trending: false,
    published: true,
    createdAt: new Date('2026-08-08'),
    updatedAt: new Date('2026-08-15'),
  },
  {
    id: 'prod-9',
    sellerId: 'seller-9',
    name: "Traditional Men's Agbada 3-Piece Set",
    description: 'Magnificent embroidered 3-piece Agbada attire including outer robe, buba shirt, and matching sokoto trousers. Intricate royal neckline embroidery.',
    category: 'Clothing',
    price: 35000,
    originalPrice: 65000,
    images: [
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1614081781451-29c084a7de30?auto=format&fit=crop&w=900&q=80',
    ],
    size: 'XL',
    condition: ProductCondition.NEW,
    material: 'Damask & Cashmere',
    color: 'Pristine White / Gold',
    brand: 'Yoruba Royal Wardrobe',
    quantity: 4,
    sold: 21,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-09'),
    updatedAt: new Date('2026-08-16'),
  },
  {
    id: 'prod-10',
    sellerId: 'seller-10',
    name: 'Handmade African Beaded Collar Necklace',
    description: 'Intricately hand-strung glass beaded collar necklace handcrafted by Nigerian artisans. Traditional geometric motifs that elevate both modern and ethnic outfits.',
    category: 'Accessories',
    price: 4500,
    originalPrice: 9000,
    images: [
      'https://images.unsplash.com/photo-1614081781451-29c084a7de30?auto=format&fit=crop&w=900&q=80',
    ],
    size: 'Adjustable',
    condition: ProductCondition.NEW,
    material: 'Glass Beads & Brass Clasp',
    color: 'Multi-color Gold & Coral',
    brand: 'AfriJewels Lagos',
    quantity: 25,
    sold: 120,
    rating: 4.7,
    trending: false,
    published: true,
    createdAt: new Date('2026-08-03'),
    updatedAt: new Date('2026-08-11'),
  },
  {
    id: 'prod-11',
    sellerId: 'seller-11',
    name: 'Luxury Silk Lace Boubou Gown',
    description: 'Breathtaking floor-length royal Boubou gown with delicate scalloped lace embroidery, sparkling crystal buttons, and free-flowing elegant drape.',
    category: 'Clothing',
    price: 26000,
    originalPrice: 48000,
    images: [
      'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=900&q=80',
    ],
    size: 'Free Size',
    condition: ProductCondition.NEW,
    material: 'Swiss Voile & Silk Lace',
    color: 'Emerald & Gold',
    brand: 'African Queen Couture',
    quantity: 7,
    sold: 42,
    rating: 4.9,
    trending: true,
    published: true,
    createdAt: new Date('2026-08-06'),
    updatedAt: new Date('2026-08-13'),
  },
  {
    id: 'prod-12',
    sellerId: 'seller-12',
    name: "Women's Pointed Ballet Flats",
    description: 'Comfortable everyday pointed slip-on flats. Cushioned inner sole, flexible grip bottom, and sleek silhouette suitable for office or casual outings.',
    category: 'Shoes',
    price: 13500,
    originalPrice: 22000,
    images: [
      '/female-shoe-flat.jpg',
    ],
    size: '39 / 40',
    condition: ProductCondition.NEW,
    material: 'Soft Faux Leather',
    color: 'Tan Beige',
    brand: 'Chic Steps',
    quantity: 11,
    sold: 37,
    rating: 4.7,
    trending: false,
    published: true,
    createdAt: new Date('2026-08-04'),
    updatedAt: new Date('2026-08-10'),
  },
];

export const getProductById = (productId: string) =>
  sampleProducts.find((product) => product.id === productId);
